[phases.setup]
aptPkgs = ["...", "libmysqlclient-dev"]


[build.commands]
install = "sudo apt-get update && sudo apt-get install -y libmysqlclient-dev && . /opt/venv/bin/activate && pip install -r requirements.txt"
