[setup]
python38 = true
libmysqlclient.dev = true
gcc = true

[build]
builder = "nixpacks"
buildCommand = "echo building!"

[deploy]
startCommand = "python manage.py migrate && gunicorn AlegriaApp.wsgi"