[build]
builder = "nixpacks"
buildCommand = "sudo apt-get update && sudo apt-get install -y libmysqlclient-dev"


[deploy]
startCommand = "python -m pip install --upgrade pip && python manage.py migrate && gunicorn AlegriaApp.wsgi"

