[setup]
python38 = true
libmysqlclient-dev = true
gcc = true

[build]
builder = "nixpacks"
buildCommand = "echo building!"

[build.packages]
libmysqlclient.dev = "8.0.26"

[deploy]
startCommand = "python -m pip install --upgrade pip && python manage.py migrate && gunicorn AlegriaApp.wsgi"