[setup]
python38 = true
gcc = true
libmysqlclient.dev = true

[build]
builder = "nixpacks"
buildCommand = "echo building!"



[deploy]
startCommand = "sudo apt-get install libmysqlclient-dev && python manage.py migrate && gunicorn AlegriaApp.wsgi"