[build]
builder = "nixpacks"
buildCommand = "echo building!"


[deploy]
startCommand = "python -m pip install --upgrade pip && python manage.py migrate && gunicorn AlegriaApp.wsgi"

[environments.production.deploy]
startCommand = "sudo apt-get update && sudo apt-get install -y libmysqlclient-dev"