# Generated by Django 4.1.7 on 2023-04-18 03:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ApiArriendosAlegria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajador',
            name='usuario_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='cuenta',
            field=models.IntegerField(verbose_name='Numero de cuenta'),
        ),
        migrations.AlterField(
            model_name='propietario',
            name='contacto_prop',
            field=models.IntegerField(verbose_name='Contacto Propietario'),
        ),
        migrations.AlterField(
            model_name='propietario',
            name='email_prop',
            field=models.EmailField(max_length=254, verbose_name='Email Propietario'),
        ),
    ]
