# Generated by Django 4.1.7 on 2023-04-18 03:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ApiArriendosAlegria', '0002_trabajador_usuario_id_alter_cuenta_cuenta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajador',
            name='usuario_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
