# Generated by Django 4.1.7 on 2023-04-18 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiArriendosAlegria', '0003_alter_trabajador_usuario_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='propietario_id',
            field=models.IntegerField(verbose_name='Propietario de la cuenta'),
        ),
    ]
