# Generated by Django 4.1.7 on 2023-04-19 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ApiArriendosAlegria", "0004_alter_cuenta_propietario_id"),
    ]

    operations = [
        migrations.RemoveField(model_name="banco", name="nic_banco",),
    ]
