# Generated by Django 4.1.7 on 2023-04-19 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ApiArriendosAlegria", "0005_remove_banco_nic_banco"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comuna",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="region",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
