# Generated by Django 4.1.7 on 2023-04-19 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ApiArriendosAlegria", "0006_alter_comuna_id_alter_region_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="region",
            name="number_reg",
            field=models.IntegerField(null=True, verbose_name="Numero Región"),
        ),
        migrations.AlterField(
            model_name="region",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
