# Generated by Django 4.1.7 on 2023-04-19 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ApiArriendosAlegria", "0007_region_number_reg_alter_region_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="region",
            name="nom_reg",
            field=models.CharField(
                max_length=250, unique=True, verbose_name="Nombre Región"
            ),
        ),
        migrations.AlterField(
            model_name="region",
            name="number_reg",
            field=models.IntegerField(
                null=True, unique=True, verbose_name="Numero Región"
            ),
        ),
    ]
