# Generated by Django 4.1.7 on 2023-04-19 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ApiArriendosAlegria", "0008_alter_region_nom_reg_alter_region_number_reg"),
    ]

    operations = [
        migrations.RemoveField(model_name="region", name="number_reg",),
        migrations.AlterField(
            model_name="region",
            name="id",
            field=models.IntegerField(
                primary_key=True, serialize=False, verbose_name="Numero Región"
            ),
        ),
    ]
