# Generated by Django 4.1.7 on 2023-04-19 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ApiArriendosAlegria", "0009_remove_region_number_reg_alter_region_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="region",
            name="orden",
            field=models.IntegerField(default=1, verbose_name="orden region"),
        ),
    ]
