# Generated by Django 4.1.7 on 2023-07-01 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ApiArriendosAlegria', '0010_remove_trabajador_usuario_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagoPropietarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateTimeField()),
                ('monto_canon', models.PositiveBigIntegerField(default=0)),
                ('monto_honorarios', models.PositiveBigIntegerField(default=0)),
                ('monto_final', models.PositiveBigIntegerField(default=0)),
                ('n_boleta', models.PositiveBigIntegerField(default=0)),
                ('detalle_arriendo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ApiArriendosAlegria.detallearriendo')),
                ('propiedad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ApiArriendosAlegria.propiedad')),
                ('servicio_extra', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ApiArriendosAlegria.serviciosextras')),
            ],
        ),
    ]
