# Generated by Django 4.1.7 on 2023-04-19 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ApiArriendosAlegria", "0012_alter_region_orden"),
    ]

    operations = [
        migrations.AlterField(
            model_name="region",
            name="orden",
            field=models.IntegerField(
                default=0, unique=True, verbose_name="orden region"
            ),
        ),
    ]
