# Generated by Django 4.1.7 on 2023-04-19 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ApiArriendosAlegria", "0013_alter_region_orden"),
    ]

    operations = [
        migrations.RemoveField(model_name="cuenta", name="propietario_id",),
        migrations.RemoveField(model_name="tipocuenta", name="banco_id",),
        migrations.RemoveField(model_name="tipocuenta", name="desc_cuenta",),
        migrations.AddField(
            model_name="cuenta",
            name="propietario_rut",
            field=models.CharField(
                default="01.234.456-7",
                max_length=12,
                verbose_name="Propietario de la cuenta",
            ),
        ),
    ]
