# Generated by Django 4.1.7 on 2023-04-19 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ApiArriendosAlegria", "0014_remove_cuenta_propietario_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="trabajador", name="cuenta",),
    ]
