# Generated by Django 4.1.7 on 2023-04-20 21:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ApiArriendosAlegria', '0015_remove_trabajador_cuenta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajador',
            name='usuario_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
