# Generated by Django 4.1.7 on 2023-04-23 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ApiArriendosAlegria", "0016_alter_trabajador_usuario_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="trabajador",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="trabajador",
            name="seg_ape_trab",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Segundo Apellido"
            ),
        ),
        migrations.AlterField(
            model_name="trabajador",
            name="seg_nom_trab",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Segundo Nombre"
            ),
        ),
    ]
