# Generated by Django 4.1.7 on 2023-05-06 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "ApiArriendosAlegria",
            "0017_trabajador_email_alter_trabajador_seg_ape_trab_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="arrendatario",
            name="seg_ape_arr",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Segundo Apellido"
            ),
        ),
        migrations.AlterField(
            model_name="arrendatario",
            name="seg_nom_arr",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Segundo Nombre"
            ),
        ),
    ]
