# Generated by Django 4.1.7 on 2023-05-06 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ApiArriendosAlegria", "0018_alter_arrendatario_seg_ape_arr_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="propietario", old_name="pri_nom_pro", new_name="pri_nom_prop",
        ),
        migrations.AlterField(
            model_name="propietario",
            name="seg_nom_prop",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Segundo Nombre"
            ),
        ),
    ]
