# Generated by Django 4.1.7 on 2023-05-07 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ApiArriendosAlegria", "0020_alter_propietario_seg_ape_prop"),
    ]

    operations = [
        migrations.AlterField(
            model_name="propiedad",
            name="rol_ppdd",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Rol propiedad"
            ),
        ),
    ]
