# Generated by Django 4.1.7 on 2023-05-07 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ApiArriendosAlegria", "0021_alter_propiedad_rol_ppdd"),
    ]

    operations = [
        migrations.AddField(
            model_name="propiedad",
            name="numero_ppdd",
            field=models.IntegerField(default=100000, verbose_name="Número Propiedad"),
        ),
    ]
