# Generated by Django 4.1.7 on 2023-05-07 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ApiArriendosAlegria", "0022_propiedad_numero_ppdd"),
    ]

    operations = [
        migrations.AlterField(
            model_name="propiedad",
            name="numero_ppdd",
            field=models.IntegerField(verbose_name="Número Propiedad"),
        ),
    ]
