# Generated by Django 4.1.7 on 2023-05-07 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ApiArriendosAlegria", "0023_alter_propiedad_numero_ppdd"),
    ]

    operations = [
        migrations.RemoveField(model_name="propiedad", name="cod_ppdd",),
    ]
