# Generated by Django 4.1.7 on 2023-05-08 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ApiArriendosAlegria", "0024_remove_propiedad_cod_ppdd"),
    ]

    operations = [
        migrations.RemoveField(model_name="arrendatario", name="cuenta",),
    ]
