# Generated by Django 4.1.7 on 2023-05-08 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiArriendosAlegria', '0025_remove_arrendatario_cuenta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedad',
            name='numero_ppdd',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número Propiedad'),
        ),
    ]
