# Generated by Django 4.1.7 on 2023-05-11 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ApiArriendosAlegria', '0026_alter_propiedad_numero_ppdd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallearriendo',
            name='propiedad_id',
        ),
        migrations.AddField(
            model_name='arriendo',
            name='propiedad_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ApiArriendosAlegria.propiedad'),
        ),
        migrations.AddField(
            model_name='detallearriendo',
            name='monto_pago',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
