# Generated by Django 4.1.7 on 2023-05-11 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ApiArriendosAlegria', '0027_remove_detallearriendo_propiedad_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propietario',
            old_name='comuna_id',
            new_name='comuna',
        ),
    ]
