# Generated by Django 4.1.7 on 2023-05-11 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ApiArriendosAlegria', '0028_rename_arrendatario_id_arriendo_arrendatario_and_more'),
        ('ApiArriendosAlegria', '0028_rename_comuna_id_propietario_comuna'),
    ]

    operations = [
    ]
