# Generated by Django 4.1.7 on 2023-05-11 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ApiArriendosAlegria', '0029_merge_20230511_1808'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propiedad',
            old_name='comuna_id',
            new_name='comuna',
        ),
        migrations.RenameField(
            model_name='trabajador',
            old_name='comuna_id',
            new_name='comuna',
        ),
    ]
