# Generated by Django 4.1.7 on 2023-05-15 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiArriendosAlegria', '0030_rename_comuna_id_propiedad_comuna_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arriendo',
            name='cod_arriendo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Codigo Arriendo'),
        ),
    ]
