# Generated by Django 4.1.7 on 2023-05-15 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiArriendosAlegria', '0031_alter_arriendo_cod_arriendo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arriendo',
            name='periodo_reajuste',
            field=models.IntegerField(verbose_name='Perdio Reajuste'),
        ),
    ]
