# Generated by Django 4.1.7 on 2023-05-15 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiArriendosAlegria', '0033_alter_arriendo_fecha_entrega'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arriendo',
            name='estado_arriendo',
            field=models.BooleanField(default=True),
        ),
    ]
