# Generated by Django 4.1.7 on 2023-05-15 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ApiArriendosAlegria', '0034_alter_arriendo_estado_arriendo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraDepartamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bodega', models.IntegerField(blank=True, null=True)),
                ('estacionamiento', models.IntegerField(blank=True, null=True)),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApiArriendosAlegria.propiedad')),
            ],
        ),
    ]
