# Generated by Django 4.1.7 on 2023-05-15 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiArriendosAlegria', '0035_extradepartamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arriendo',
            name='fecha_pri_ajuste',
        ),
        migrations.AlterField(
            model_name='arriendo',
            name='fecha_inicio',
            field=models.DateTimeField(verbose_name='Fecha de Inicio'),
        ),
    ]
