# Generated by Django 4.1.7 on 2023-05-15 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiArriendosAlegria', '0036_remove_arriendo_fecha_pri_ajuste_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='arriendo',
            name='fecha_pri_ajuste',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='arriendo',
            name='fecha_entrega',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha entrega arriendo'),
        ),
        migrations.AlterField(
            model_name='arriendo',
            name='fecha_termino',
            field=models.DateTimeField(verbose_name='Fecha de Termino'),
        ),
        migrations.AlterField(
            model_name='detallearriendo',
            name='fecha_pago',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='gastocomun',
            name='fecha',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='serviciosextras',
            name='fecha',
            field=models.DateTimeField(),
        ),
    ]
