# Generated by Django 4.1.7 on 2023-05-15 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiArriendosAlegria', '0037_arriendo_fecha_pri_ajuste_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arriendo',
            name='fecha_pri_ajuste',
            field=models.DateTimeField(),
        ),
    ]
