# Generated by Django 4.1.7 on 2023-05-15 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiArriendosAlegria', '0038_alter_arriendo_fecha_pri_ajuste'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arriendo',
            name='fecha_pri_ajuste',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
