# Generated by Django 4.1.7 on 2023-05-15 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ApiArriendosAlegria", "0039_alter_arriendo_fecha_pri_ajuste"),
    ]

    operations = [
        migrations.RemoveField(model_name="extradepartamento", name="bodega",),
        migrations.RemoveField(model_name="extradepartamento", name="estacionamiento",),
        migrations.AddField(
            model_name="extradepartamento",
            name="arriendo",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ApiArriendosAlegria.arriendo",
            ),
        ),
    ]
