# Generated by Django 4.1.7 on 2023-05-15 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ApiArriendosAlegria", "0040_remove_extradepartamento_bodega_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ExtraDepartamento", new_name="ArriendoDepartamento",
        ),
    ]
