# Generated by Django 4.1.7 on 2023-05-17 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiArriendosAlegria', '0042_propiedad_nro_bodega_propiedad_nro_estacionamiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedad',
            name='nro_bodega',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Número Bodega'),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='nro_estacionamiento',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Número Estacionamiento'),
        ),
    ]
