# Generated by Django 4.1.7 on 2023-05-22 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiArriendosAlegria', '0043_alter_propiedad_nro_bodega_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='cuenta',
            field=models.PositiveBigIntegerField(verbose_name='Numero de cuenta'),
        ),
    ]
