# Generated by Django 4.1.7 on 2023-05-22 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ApiArriendosAlegria", "0044_alter_cuenta_cuenta"),
    ]

    operations = [
        migrations.AddField(
            model_name="cuenta",
            name="rut_tercero",
            field=models.CharField(
                default="01.234.456-7",
                max_length=12,
                verbose_name="Propietario de la cuenta",
            ),
        ),
    ]
