# Generated by Django 4.1.7 on 2023-05-22 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ApiArriendosAlegria", "0045_cuenta_rut_tercero"),
    ]

    operations = [
        migrations.AddField(
            model_name="propiedad",
            name="cod",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
