# Generated by Django 4.1.7 on 2023-05-23 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiArriendosAlegria', '0046_propiedad_cod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='rut_tercero',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Propietario de la cuenta'),
        ),
    ]
