# Generated by Django 4.1.7 on 2023-05-23 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiArriendosAlegria', '0047_alter_cuenta_rut_tercero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='rut_tercero',
            field=models.CharField(blank=True, default='111.111.111-1', max_length=12, null=True, verbose_name='Propietario de la cuenta'),
        ),
    ]
