# Generated by Django 4.1.7 on 2023-05-29 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiArriendosAlegria', '0049_alter_propiedad_numero_ppdd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arriendo',
            name='cod_arriendo',
        ),
        migrations.AddField(
            model_name='arriendo',
            name='cod_esbio',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Código ESSBIO'),
        ),
        migrations.AddField(
            model_name='arriendo',
            name='cod_gassur',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Código GasSur'),
        ),
        migrations.AddField(
            model_name='arriendo',
            name='cod_luz',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Código Luz'),
        ),
        migrations.AddField(
            model_name='arriendo',
            name='comision',
            field=models.FloatField(blank=True, null=True, verbose_name='Comisión'),
        ),
        migrations.AddField(
            model_name='arriendo',
            name='porcentaje_1',
            field=models.FloatField(blank=True, null=True, verbose_name='Porcentaje 1'),
        ),
        migrations.AddField(
            model_name='arriendo',
            name='porcentaje_2',
            field=models.FloatField(blank=True, null=True, verbose_name='Porcentaje 2'),
        ),
    ]
