# Generated by Django 4.1.7 on 2023-05-29 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiArriendosAlegria', '0050_remove_arriendo_cod_arriendo_arriendo_cod_esbio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='arriendo',
            name='dia_pago',
            field=models.IntegerField(blank=True, null=True, verbose_name='Día de pago (nro.)'),
        ),
    ]
