# Generated by Django 4.1.7 on 2023-05-29 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ApiArriendosAlegria', '0051_arriendo_dia_pago'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arriendo',
            name='porcentaje_multa',
        ),
        migrations.CreateModel(
            name='PorcentajeMulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje', models.IntegerField(verbose_name='Porcentaje Multa')),
                ('arriendo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApiArriendosAlegria.arriendo')),
            ],
        ),
    ]
