# Generated by Django 4.1.7 on 2023-06-01 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiArriendosAlegria', '0052_remove_arriendo_porcentaje_multa_porcentajemulta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arriendo',
            name='cod_esbio',
        ),
        migrations.RemoveField(
            model_name='arriendo',
            name='cod_gassur',
        ),
        migrations.RemoveField(
            model_name='arriendo',
            name='cod_luz',
        ),
        migrations.AddField(
            model_name='propiedad',
            name='agua',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Código ESSBIO'),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='gas',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Código Gas'),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='luz',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Código Luz'),
        ),
    ]
