# Generated by Django 4.1.7 on 2023-06-01 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ApiArriendosAlegria', '0053_remove_arriendo_cod_esbio_remove_arriendo_cod_gassur_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PorcentajeMulta',
        ),
    ]
