# Generated by Django 4.1.7 on 2023-06-01 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiArriendosAlegria', '0054_delete_porcentajemulta'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValoresGlobales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('valor', models.IntegerField(verbose_name='Porcentaje Multa')),
            ],
        ),
    ]
