# Generated by Django 4.1.7 on 2023-06-01 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ApiArriendosAlegria', '0055_valoresglobales'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personalidadjuridica',
            old_name='rol',
            new_name='rut',
        ),
        migrations.RemoveField(
            model_name='personalidadjuridica',
            name='propietario',
        ),
        migrations.RemoveField(
            model_name='personalidadjuridica',
            name='representante',
        ),
        migrations.AddField(
            model_name='personalidadjuridica',
            name='comuna',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ApiArriendosAlegria.comuna'),
        ),
        migrations.AddField(
            model_name='personalidadjuridica',
            name='contacto',
            field=models.IntegerField(blank=True, null=True, verbose_name='Contacto'),
        ),
        migrations.AddField(
            model_name='personalidadjuridica',
            name='direccion',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Dirección Principal'),
        ),
        migrations.AddField(
            model_name='personalidadjuridica',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='propietario',
            name='personalidad_juridica',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ApiArriendosAlegria.personalidadjuridica'),
        ),
    ]
