# Generated by Django 4.1.7 on 2023-06-01 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiArriendosAlegria', '0056_rename_rol_personalidadjuridica_rut_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valoresglobales',
            name='valor',
            field=models.FloatField(),
        ),
    ]
