# Generated by Django 4.1.7 on 2023-06-02 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ApiArriendosAlegria', '0057_alter_valoresglobales_valor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Externo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('contacto', models.IntegerField(verbose_name='Contacto')),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo')),
                ('rol', models.CharField(max_length=50, verbose_name='Rol')),
            ],
        ),
        migrations.AddField(
            model_name='arriendo',
            name='observaciones',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones adicionales sobre el arriendo'),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='es_valor_uf',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='valor_arriendo_base',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Valor Arriendo Base'),
        ),
        migrations.AddField(
            model_name='propietario',
            name='pctje_cobro_honorario',
            field=models.FloatField(blank=True, null=True, verbose_name='Porcentaje Contacto Propietario'),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='cod',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='arriendo',
            name='externo',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ApiArriendosAlegria.externo'),
        ),
    ]
