# Generated by Django 4.1.7 on 2023-06-03 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiArriendosAlegria', '0058_externo_arriendo_observaciones_propiedad_es_valor_uf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalidadjuridica',
            name='rut',
            field=models.CharField(max_length=80),
        ),
    ]
