# Generated by Django 4.1.7 on 2023-06-03 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiArriendosAlegria', '0059_alter_personalidadjuridica_rut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externo',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
