# Generated by Django 4.1.7 on 2023-06-03 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiArriendosAlegria', '0060_alter_externo_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arriendo',
            name='porcentaje_1',
        ),
        migrations.RemoveField(
            model_name='arriendo',
            name='porcentaje_2',
        ),
        migrations.AlterField(
            model_name='propietario',
            name='pctje_cobro_honorario',
            field=models.FloatField(blank=True, null=True, verbose_name='Porcentaje Cobro Propietario'),
        ),
    ]
