# Generated by Django 4.1.7 on 2023-06-03 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ApiArriendosAlegria", "0061_remove_arriendo_porcentaje_1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="externo",
            name="rut",
            field=models.CharField(
                blank=True, max_length=12, null=True, verbose_name="rut externo"
            ),
        ),
    ]
