# Generated by Django 4.1.7 on 2023-06-03 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ApiArriendosAlegria", "0062_externo_rut"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cuenta",
            name="rut_tercero",
            field=models.CharField(
                blank=True,
                default="11.111.111-1",
                max_length=12,
                null=True,
                verbose_name="Propietario de la cuenta",
            ),
        ),
    ]
