# Generated by Django 4.1.7 on 2023-06-04 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiArriendosAlegria', '0064_alter_propietario_pctje_cobro_honorario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arriendo',
            old_name='fecha_pri_ajuste',
            new_name='fecha_pri_reajuste',
        ),
        migrations.RenameField(
            model_name='detallearriendo',
            old_name='fecha_pago',
            new_name='fecha_a_pagar',
        ),
        migrations.RenameField(
            model_name='detallearriendo',
            old_name='monto_pago',
            new_name='monto_a_pagar',
        ),
        migrations.RemoveField(
            model_name='arriendo',
            name='monto_arriendo',
        ),
        migrations.AddField(
            model_name='detallearriendo',
            name='fecha_pagada',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='detallearriendo',
            name='monto_pagado',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
