# Generated by Django 4.1.7 on 2023-06-05 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiArriendosAlegria', '0066_rename_fecha_pri_reajuste_arriendo_fecha_reajuste_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallearriendo',
            name='valor_multa',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
