# Generated by Django 4.1.7 on 2023-06-05 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ApiArriendosAlegria', '0067_detallearriendo_valor_multa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviciosextras',
            name='Monto',
        ),
        migrations.AddField(
            model_name='serviciosextras',
            name='contador_cuotas',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='serviciosextras',
            name='externo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ApiArriendosAlegria.externo'),
        ),
        migrations.AddField(
            model_name='serviciosextras',
            name='monto_cuota',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='serviciosextras',
            name='nro_cuotas',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='serviciosextras',
            name='propiedad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ApiArriendosAlegria.propiedad'),
        ),
        migrations.AlterField(
            model_name='serviciosextras',
            name='arriendo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ApiArriendosAlegria.arriendo'),
        ),
        migrations.AddField(
            model_name='serviciosextras',
            name='monto',
            field=models.IntegerField(default=0),
        ),
    ]
