# Generated by Django 4.1.7 on 2023-06-05 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiArriendosAlegria', '0068_remove_serviciosextras_monto_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviciosextras',
            old_name='monto_cuota',
            new_name='monto_cuotas',
        ),
        migrations.AlterField(
            model_name='serviciosextras',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
