# Generated by Django 4.1.7 on 2023-06-05 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiArriendosAlegria', '0069_rename_monto_cuota_serviciosextras_monto_cuotas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='incluye_gc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='valor_gasto_comun',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
