# Generated by Django 4.1.7 on 2023-06-05 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ApiArriendosAlegria', '0065_rename_fecha_pri_ajuste_arriendo_fecha_reajuste_and_more'),
        ('ApiArriendosAlegria', '0070_propiedad_incluye_gc_propiedad_valor_gasto_comun'),
    ]

    operations = [
    ]
